version: '3'
services:
  sierratakehomeapi:
    image: sierratakehomeapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqlserver;Database=SierraTakeHome_DB;User Id=sa;Password=Test@123;
    build:
      dockerfile: SierraTakeHome.API\Dockerfile
    ports:
      - "3500:80"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test@123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./scripts:/scripts
    command: /bin/bash ./scripts/init_database.sh